---
- name: Extract java tar to opt java
  ansible.builtin.unarchive:
    src: /install/java/jre-8u281-linux-x64.tar.gz
    dest: /opt/
    remote_src: yes

- name: symlink kafka to kafka version
  ansible.builtin.file:
    src: /opt/jre1.8.0_281
    dest: /opt/java
    state: link

- name: Update java configuration in global profile
  blockinfile:
    path: /etc/profile.d/java-path.sh
    create: yes
    block: |
      export JAVA_HOME=/opt/java
      export PATH=${PATH}:${JAVA_HOME}/bin